// Code generated by Slice Machine. DO NOT EDIT.

import type * as prismic from "@prismicio/client";

type Simplify<T> = { [KeyType in keyof T]: T[KeyType] };

/**
 * Content for Book documents
 */
interface BookDocumentData {
  /**
   * BookTitle field in *Book*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: book.booktitle
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  booktitle: prismic.KeyTextField;

  /**
   * Book Cover field in *Book*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: book.bookcover
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  bookcover: prismic.ImageField<never>;

  /**
   * Amazon URL field in *Book*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: book.amazonurl
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  amazonurl: prismic.LinkField<
    string,
    string,
    unknown,
    prismic.FieldState,
    never
  >;

  /**
   * Book Series field in *Book*
   *
   * - **Field Type**: Content Relationship
   * - **Placeholder**: *None*
   * - **API ID Path**: book.bookseries
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  bookseries: prismic.ContentRelationshipField;

  /**
   * Book Publish Date field in *Book*
   *
   * - **Field Type**: Date
   * - **Placeholder**: *None*
   * - **API ID Path**: book.bookpublishdate
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#date
   */
  bookpublishdate: prismic.DateField;
}

/**
 * Book document from Prismic
 *
 * - **API ID**: `book`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type BookDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<Simplify<BookDocumentData>, "book", Lang>;

type HomepageDocumentDataSlicesSlice =
  | SeriesHeroSlice
  | CarouselSlice
  | ProseSlice
  | MailerLiteSignUpSlice
  | HeroWithFigureSlice;

/**
 * Content for Homepage documents
 */
interface HomepageDocumentData {
  /**
   * Homepage Meta Description field in *Homepage*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: homepage.homepagemetadescription
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  homepagemetadescription: prismic.KeyTextField;

  /**
   * Homepage Meta Image field in *Homepage*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: homepage.homepagemetaimage
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  homepagemetaimage: prismic.ImageField<never>;

  /**
   * Slice Zone field in *Homepage*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: homepage.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<HomepageDocumentDataSlicesSlice> /**
   * Meta Description field in *Homepage*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: homepage.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *Homepage*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: homepage.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  meta_image: prismic.ImageField<never>;

  /**
   * Meta Title field in *Homepage*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: homepage.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_title: prismic.KeyTextField;
}

/**
 * Homepage document from Prismic
 *
 * - **API ID**: `homepage`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type HomepageDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<HomepageDocumentData>,
    "homepage",
    Lang
  >;

/**
 * Item in *Main Navigation → Navigation Links*
 */
export interface MainNavigationDocumentDataNavigationlinksItem {
  /**
   * Menu Item Text field in *Main Navigation → Navigation Links*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: main_navigation.navigationlinks[].menuitemtext
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  menuitemtext: prismic.KeyTextField;

  /**
   * Menu Item field in *Main Navigation → Navigation Links*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: main_navigation.navigationlinks[].menuitem
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  menuitem: prismic.LinkField<
    string,
    string,
    unknown,
    prismic.FieldState,
    "default" | "destructive" | "ghost" | "link" | "outline" | "secondary"
  >;
}

/**
 * Item in *Main Navigation → SocialLinks*
 */
export interface MainNavigationDocumentDataSociallinksItem {
  /**
   * SocialLink field in *Main Navigation → SocialLinks*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: main_navigation.sociallinks[].sociallink
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  sociallink: prismic.LinkField<
    string,
    string,
    unknown,
    prismic.FieldState,
    never
  >;

  /**
   * SocialPlatform field in *Main Navigation → SocialLinks*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **API ID Path**: main_navigation.sociallinks[].socialplatform
   * - **Documentation**: https://prismic.io/docs/field#select
   */
  socialplatform: prismic.SelectField<
    "Facebook" | "Instagram" | "TikTok" | "Twitter"
  >;
}

/**
 * Content for Main Navigation documents
 */
interface MainNavigationDocumentData {
  /**
   * Logo field in *Main Navigation*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: main_navigation.logo
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  logo: prismic.ImageField<never>;

  /**
   * Navigation Links field in *Main Navigation*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: main_navigation.navigationlinks[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  navigationlinks: prismic.GroupField<
    Simplify<MainNavigationDocumentDataNavigationlinksItem>
  >;

  /**
   * SocialLinks field in *Main Navigation*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: main_navigation.sociallinks[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  sociallinks: prismic.GroupField<
    Simplify<MainNavigationDocumentDataSociallinksItem>
  >;
}

/**
 * Main Navigation document from Prismic
 *
 * - **API ID**: `main_navigation`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type MainNavigationDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<MainNavigationDocumentData>,
    "main_navigation",
    Lang
  >;

type PageDocumentDataSlicesSlice =
  | ContentIndexSlice
  | CarouselSlice
  | HeroWithFigureSlice
  | ProseSlice
  | MailerLiteSignUpSlice;

/**
 * Content for Page documents
 */
interface PageDocumentData {
  /**
   * Page Title field in *Page*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: page.pagetitle
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  pagetitle: prismic.KeyTextField;

  /**
   * Slice Zone field in *Page*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: page.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<PageDocumentDataSlicesSlice> /**
   * Meta Description field in *Page*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: page.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  meta_description: prismic.KeyTextField;

  /**
   * Meta Title field in *Page*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: page.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_title: prismic.KeyTextField;

  /**
   * Meta Image field in *Page*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: page.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  meta_image: prismic.ImageField<never>;
}

/**
 * Page document from Prismic
 *
 * - **API ID**: `page`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type PageDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<Simplify<PageDocumentData>, "page", Lang>;

type PostDocumentDataSlicesSlice =
  | CarouselSlice
  | MailerLiteSignUpSlice
  | SeriesHeroSlice
  | HeroWithFigureSlice
  | ProseSlice;

/**
 * Content for Post documents
 */
interface PostDocumentData {
  /**
   * Title field in *Post*
   *
   * - **Field Type**: Title
   * - **Placeholder**: The title of your post
   * - **API ID Path**: post.title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title: prismic.TitleField;

  /**
   * Excerpt field in *Post*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: post.excerpt
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  excerpt: prismic.RichTextField;

  /**
   * Slice Zone field in *Post*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: post.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<PostDocumentDataSlicesSlice> /**
   * Meta Description field in *Post*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: post.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *Post*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: post.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  meta_image: prismic.ImageField<never>;

  /**
   * Meta Title field in *Post*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: post.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_title: prismic.KeyTextField;
}

/**
 * Post document from Prismic
 *
 * - **API ID**: `post`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type PostDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<Simplify<PostDocumentData>, "post", Lang>;

/**
 * Item in *Series → Series Books*
 */
export interface SeriesDocumentDataSeriesbooksItem {
  /**
   * Series Book field in *Series → Series Books*
   *
   * - **Field Type**: Content Relationship
   * - **Placeholder**: *None*
   * - **API ID Path**: series.seriesbooks[].seriesbook
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  seriesbook: prismic.ContentRelationshipField<"book">;
}

/**
 * Content for Series documents
 */
interface SeriesDocumentData {
  /**
   * Series Name field in *Series*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: series.seriesname
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  seriesname: prismic.KeyTextField;

  /**
   * Series Box Set Image field in *Series*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: series.seriesimage
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  seriesimage: prismic.ImageField<never>;

  /**
   * Series Books field in *Series*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: series.seriesbooks[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  seriesbooks: prismic.GroupField<Simplify<SeriesDocumentDataSeriesbooksItem>>;

  /**
   * Box Set Link field in *Series*
   *
   * - **Field Type**: Link
   * - **Placeholder**: Enter link to box set (amazon)
   * - **API ID Path**: series.boxsetlink
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  boxsetlink: prismic.LinkField<
    string,
    string,
    unknown,
    prismic.FieldState,
    never
  >;
}

/**
 * Series document from Prismic
 *
 * - **API ID**: `series`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type SeriesDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<Simplify<SeriesDocumentData>, "series", Lang>;

export type AllDocumentTypes =
  | BookDocument
  | HomepageDocument
  | MainNavigationDocument
  | PageDocument
  | PostDocument
  | SeriesDocument;

/**
 * Primary content in *Carousel → Default → Primary*
 */
export interface CarouselSliceDefaultPrimary {
  /**
   * Carousel Title field in *Carousel → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: carousel.default.primary.carouseltitle
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  carouseltitle: prismic.KeyTextField;

  /**
   * Carousel Description field in *Carousel → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: carousel.default.primary.carouseldescription
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  carouseldescription: prismic.RichTextField;
}

/**
 * Primary content in *Carousel → Items*
 */
export interface CarouselSliceDefaultItem {
  /**
   * CarouselImage field in *Carousel → Items*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: carousel.items[].carouselimage
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  carouselimage: prismic.ImageField<never>;

  /**
   * CarouselImageLink field in *Carousel → Items*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: carousel.items[].carouselimagelink
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  carouselimagelink: prismic.LinkField<
    string,
    string,
    unknown,
    prismic.FieldState,
    never
  >;
}

/**
 * Default variation for Carousel Slice
 *
 * - **API ID**: `default`
 * - **Description**: Carousel
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type CarouselSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<CarouselSliceDefaultPrimary>,
  Simplify<CarouselSliceDefaultItem>
>;

/**
 * Slice variation for *Carousel*
 */
type CarouselSliceVariation = CarouselSliceDefault;

/**
 * Carousel Shared Slice
 *
 * - **API ID**: `carousel`
 * - **Description**: Carousel
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type CarouselSlice = prismic.SharedSlice<
  "carousel",
  CarouselSliceVariation
>;

/**
 * Primary content in *ContentIndex → Default → Primary*
 */
export interface ContentIndexSliceDefaultPrimary {
  /**
   * Content Type field in *ContentIndex → Default → Primary*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **Default Value**: post
   * - **API ID Path**: content_index.default.primary.content_type
   * - **Documentation**: https://prismic.io/docs/field#select
   */
  content_type: prismic.SelectField<"post" | "book", "filled">;

  /**
   * Fallback Item Image field in *ContentIndex → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: content_index.default.primary.fallback_item_image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  fallback_item_image: prismic.ImageField<never>;

  /**
   * Number to Display field in *ContentIndex → Default → Primary*
   *
   * - **Field Type**: Number
   * - **Placeholder**: *None*
   * - **API ID Path**: content_index.default.primary.number_to_display
   * - **Documentation**: https://prismic.io/docs/field#number
   */
  number_to_display: prismic.NumberField;

  /**
   * Content CTA Text field in *ContentIndex → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: What should the buttons say?
   * - **API ID Path**: content_index.default.primary.content_cta_text
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  content_cta_text: prismic.KeyTextField;
}

/**
 * Default variation for ContentIndex Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ContentIndexSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<ContentIndexSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *ContentIndex*
 */
type ContentIndexSliceVariation = ContentIndexSliceDefault;

/**
 * ContentIndex Shared Slice
 *
 * - **API ID**: `content_index`
 * - **Description**: ContentIndex
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ContentIndexSlice = prismic.SharedSlice<
  "content_index",
  ContentIndexSliceVariation
>;

/**
 * Primary content in *HeroWithFigure → Default → Primary*
 */
export interface HeroWithFigureSliceDefaultPrimary {
  /**
   * Hero Figure field in *HeroWithFigure → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: hero_with_figure.default.primary.herofigure
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  herofigure: prismic.ImageField<never>;

  /**
   * Figure Location field in *HeroWithFigure → Default → Primary*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **Default Value**: false
   * - **API ID Path**: hero_with_figure.default.primary.herofigurelocation
   * - **Documentation**: https://prismic.io/docs/field#boolean
   */
  herofigurelocation: prismic.BooleanField;

  /**
   * Hero Heading field in *HeroWithFigure → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero_with_figure.default.primary.heroheading
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  heroheading: prismic.KeyTextField;

  /**
   * Hero Text field in *HeroWithFigure → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero_with_figure.default.primary.herotext
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  herotext: prismic.RichTextField;

  /**
   * Button Link field in *HeroWithFigure → Default → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: hero_with_figure.default.primary.herobuttonlink
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  herobuttonlink: prismic.LinkField<
    string,
    string,
    unknown,
    prismic.FieldState,
    "default" | "secondary" | "ghost" | "outline" | "destructive" | "link"
  >;

  /**
   * Hero Background Color field in *HeroWithFigure → Default → Primary*
   *
   * - **Field Type**: Color
   * - **Placeholder**: *None*
   * - **API ID Path**: hero_with_figure.default.primary.herobackgroundcolor
   * - **Documentation**: https://prismic.io/docs/field#color
   */
  herobackgroundcolor: prismic.ColorField;
}

/**
 * Default variation for HeroWithFigure Slice
 *
 * - **API ID**: `default`
 * - **Description**: HeroWithFigure
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type HeroWithFigureSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<HeroWithFigureSliceDefaultPrimary>,
  never
>;

/**
 * Primary content in *HeroWithFigure → Hero With Figure - Gradient → Primary*
 */
export interface HeroWithFigureSliceHeroWithFigureGradientPrimary {
  /**
   * Hero Figure field in *HeroWithFigure → Hero With Figure - Gradient → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: hero_with_figure.heroWithFigureGradient.primary.herofigure
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  herofigure: prismic.ImageField<never>;

  /**
   * Figure Location field in *HeroWithFigure → Hero With Figure - Gradient → Primary*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **Default Value**: false
   * - **API ID Path**: hero_with_figure.heroWithFigureGradient.primary.herofigurelocation
   * - **Documentation**: https://prismic.io/docs/field#boolean
   */
  herofigurelocation: prismic.BooleanField;

  /**
   * Hero Heading field in *HeroWithFigure → Hero With Figure - Gradient → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero_with_figure.heroWithFigureGradient.primary.heroheading
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  heroheading: prismic.KeyTextField;

  /**
   * Hero Text field in *HeroWithFigure → Hero With Figure - Gradient → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero_with_figure.heroWithFigureGradient.primary.herotext
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  herotext: prismic.RichTextField;

  /**
   * Button Text field in *HeroWithFigure → Hero With Figure - Gradient → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero_with_figure.heroWithFigureGradient.primary.herobuttontext
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  herobuttontext: prismic.KeyTextField;

  /**
   * Button Link field in *HeroWithFigure → Hero With Figure - Gradient → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: hero_with_figure.heroWithFigureGradient.primary.herobuttonlink
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  herobuttonlink: prismic.LinkField<
    string,
    string,
    unknown,
    prismic.FieldState,
    never
  >;

  /**
   * Hero Background Color Start field in *HeroWithFigure → Hero With Figure - Gradient → Primary*
   *
   * - **Field Type**: Color
   * - **Placeholder**: *None*
   * - **API ID Path**: hero_with_figure.heroWithFigureGradient.primary.herobackgroundcolorstart
   * - **Documentation**: https://prismic.io/docs/field#color
   */
  herobackgroundcolorstart: prismic.ColorField;

  /**
   * Hero Background Color End field in *HeroWithFigure → Hero With Figure - Gradient → Primary*
   *
   * - **Field Type**: Color
   * - **Placeholder**: *None*
   * - **API ID Path**: hero_with_figure.heroWithFigureGradient.primary.herobackgroundcolorend
   * - **Documentation**: https://prismic.io/docs/field#color
   */
  herobackgroundcolorend: prismic.ColorField;
}

/**
 * Hero With Figure - Gradient variation for HeroWithFigure Slice
 *
 * - **API ID**: `heroWithFigureGradient`
 * - **Description**: HeroWithFigure
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type HeroWithFigureSliceHeroWithFigureGradient =
  prismic.SharedSliceVariation<
    "heroWithFigureGradient",
    Simplify<HeroWithFigureSliceHeroWithFigureGradientPrimary>,
    never
  >;

/**
 * Primary content in *HeroWithFigure → HeroWithBackgroundImage → Primary*
 */
export interface HeroWithFigureSliceHeroWithBackgroundImagePrimary {
  /**
   * Hero Figure field in *HeroWithFigure → HeroWithBackgroundImage → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: hero_with_figure.heroWithBackgroundImage.primary.herofigure
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  herofigure: prismic.ImageField<never>;

  /**
   * Figure Location field in *HeroWithFigure → HeroWithBackgroundImage → Primary*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **Default Value**: false
   * - **API ID Path**: hero_with_figure.heroWithBackgroundImage.primary.herofigurelocation
   * - **Documentation**: https://prismic.io/docs/field#boolean
   */
  herofigurelocation: prismic.BooleanField;

  /**
   * Hero Heading field in *HeroWithFigure → HeroWithBackgroundImage → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero_with_figure.heroWithBackgroundImage.primary.heroheading
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  heroheading: prismic.KeyTextField;

  /**
   * Hero Text field in *HeroWithFigure → HeroWithBackgroundImage → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero_with_figure.heroWithBackgroundImage.primary.herotext
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  herotext: prismic.RichTextField;

  /**
   * Button Text field in *HeroWithFigure → HeroWithBackgroundImage → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero_with_figure.heroWithBackgroundImage.primary.herobuttontext
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  herobuttontext: prismic.KeyTextField;

  /**
   * Button Link field in *HeroWithFigure → HeroWithBackgroundImage → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: hero_with_figure.heroWithBackgroundImage.primary.herobuttonlink
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  herobuttonlink: prismic.LinkField<
    string,
    string,
    unknown,
    prismic.FieldState,
    never
  >;

  /**
   * Hero Background Image field in *HeroWithFigure → HeroWithBackgroundImage → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: hero_with_figure.heroWithBackgroundImage.primary.herobackgroundimage
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  herobackgroundimage: prismic.ImageField<never>;
}

/**
 * HeroWithBackgroundImage variation for HeroWithFigure Slice
 *
 * - **API ID**: `heroWithBackgroundImage`
 * - **Description**: HeroWithFigure
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type HeroWithFigureSliceHeroWithBackgroundImage =
  prismic.SharedSliceVariation<
    "heroWithBackgroundImage",
    Simplify<HeroWithFigureSliceHeroWithBackgroundImagePrimary>,
    never
  >;

/**
 * Slice variation for *HeroWithFigure*
 */
type HeroWithFigureSliceVariation =
  | HeroWithFigureSliceDefault
  | HeroWithFigureSliceHeroWithFigureGradient
  | HeroWithFigureSliceHeroWithBackgroundImage;

/**
 * HeroWithFigure Shared Slice
 *
 * - **API ID**: `hero_with_figure`
 * - **Description**: HeroWithFigure
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type HeroWithFigureSlice = prismic.SharedSlice<
  "hero_with_figure",
  HeroWithFigureSliceVariation
>;

/**
 * Primary content in *NewsletterSignUp → Default → Primary*
 */
export interface MailerLiteSignUpSliceDefaultPrimary {
  /**
   * Title field in *NewsletterSignUp → Default → Primary*
   *
   * - **Field Type**: Title
   * - **Placeholder**: Sign-up Call to Action
   * - **API ID Path**: mailer_lite_sign_up.default.primary.title
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title: prismic.TitleField;

  /**
   * Description field in *NewsletterSignUp → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: The reason to subscribe...
   * - **API ID Path**: mailer_lite_sign_up.default.primary.description
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  description: prismic.RichTextField;

  /**
   * Placeholder Text field in *NewsletterSignUp → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: What the empty field says
   * - **API ID Path**: mailer_lite_sign_up.default.primary.placeholdertext
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  placeholdertext: prismic.KeyTextField;

  /**
   * Button Text field in *NewsletterSignUp → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: What the button says
   * - **API ID Path**: mailer_lite_sign_up.default.primary.buttontext
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  buttontext: prismic.KeyTextField;

  /**
   * Form Location field in *NewsletterSignUp → Default → Primary*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **Default Value**: false
   * - **API ID Path**: mailer_lite_sign_up.default.primary.formlocation
   * - **Documentation**: https://prismic.io/docs/field#boolean
   */
  formlocation: prismic.BooleanField;

  /**
   * Button Color field in *NewsletterSignUp → Default → Primary*
   *
   * - **Field Type**: Select
   * - **Placeholder**: Select button color
   * - **Default Value**: default
   * - **API ID Path**: mailer_lite_sign_up.default.primary.buttoncolor
   * - **Documentation**: https://prismic.io/docs/field#select
   */
  buttoncolor: prismic.SelectField<
    "default" | "secondary" | "outline" | "destructive" | "ghost" | "link",
    "filled"
  >;
}

/**
 * Primary content in *NewsletterSignUp → Items*
 */
export interface MailerLiteSignUpSliceDefaultItem {
  /**
   * MailerLiteGroupName field in *NewsletterSignUp → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: mailer_lite_sign_up.items[].mailerlitegroupname
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  mailerlitegroupname: prismic.KeyTextField;

  /**
   * MailerLite Group ID field in *NewsletterSignUp → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: enter the group ID #
   * - **API ID Path**: mailer_lite_sign_up.items[].mailerlitegroupid
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  mailerlitegroupid: prismic.KeyTextField;
}

/**
 * Default variation for NewsletterSignUp Slice
 *
 * - **API ID**: `default`
 * - **Description**: MailerLiteSignUp
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type MailerLiteSignUpSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<MailerLiteSignUpSliceDefaultPrimary>,
  Simplify<MailerLiteSignUpSliceDefaultItem>
>;

/**
 * Slice variation for *NewsletterSignUp*
 */
type MailerLiteSignUpSliceVariation = MailerLiteSignUpSliceDefault;

/**
 * NewsletterSignUp Shared Slice
 *
 * - **API ID**: `mailer_lite_sign_up`
 * - **Description**: MailerLiteSignUp
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type MailerLiteSignUpSlice = prismic.SharedSlice<
  "mailer_lite_sign_up",
  MailerLiteSignUpSliceVariation
>;

/**
 * Primary content in *Prose → Default → Primary*
 */
export interface ProseSliceDefaultPrimary {
  /**
   * Prose Content field in *Prose → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: Add your content here
   * - **API ID Path**: prose.default.primary.prosecontent
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  prosecontent: prismic.RichTextField;
}

/**
 * Default variation for Prose Slice
 *
 * - **API ID**: `default`
 * - **Description**: Prose
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ProseSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<ProseSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *Prose*
 */
type ProseSliceVariation = ProseSliceDefault;

/**
 * Prose Shared Slice
 *
 * - **API ID**: `prose`
 * - **Description**: Prose
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ProseSlice = prismic.SharedSlice<"prose", ProseSliceVariation>;

/**
 * Item in *SeriesHero → Default → Primary → Series*
 */
export interface SeriesHeroSliceDefaultPrimarySeriesItem {
  /**
   * Series field in *SeriesHero → Default → Primary → Series*
   *
   * - **Field Type**: Content Relationship
   * - **Placeholder**: *None*
   * - **API ID Path**: series_hero.default.primary.series[].series
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  series: prismic.ContentRelationshipField<"series">;

  /**
   * Series Link field in *SeriesHero → Default → Primary → Series*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: series_hero.default.primary.series[].series_link
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  series_link: prismic.LinkField<
    string,
    string,
    unknown,
    prismic.FieldState,
    never
  >;
}

/**
 * Primary content in *SeriesHero → Default → Primary*
 */
export interface SeriesHeroSliceDefaultPrimary {
  /**
   * Title field in *SeriesHero → Default → Primary*
   *
   * - **Field Type**: Title
   * - **Placeholder**: Series Hero Title (Jamie Whitmann)
   * - **API ID Path**: series_hero.default.primary.title
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title: prismic.TitleField;

  /**
   * Subtitle field in *SeriesHero → Default → Primary*
   *
   * - **Field Type**: Title
   * - **Placeholder**: Subtitle (Clean Romance with HEA)
   * - **API ID Path**: series_hero.default.primary.subtitle
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  subtitle: prismic.TitleField;

  /**
   * Description field in *SeriesHero → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: Describe author or featured series
   * - **API ID Path**: series_hero.default.primary.description
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  description: prismic.RichTextField;

  /**
   * Background Color field in *SeriesHero → Default → Primary*
   *
   * - **Field Type**: Color
   * - **Placeholder**: *None*
   * - **API ID Path**: series_hero.default.primary.backgroundcolor
   * - **Documentation**: https://prismic.io/docs/field#color
   */
  backgroundcolor: prismic.ColorField;

  /**
   * Series field in *SeriesHero → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: series_hero.default.primary.series[]
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  series: prismic.GroupField<Simplify<SeriesHeroSliceDefaultPrimarySeriesItem>>;
}

/**
 * Default variation for SeriesHero Slice
 *
 * - **API ID**: `default`
 * - **Description**: SeriesHero
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type SeriesHeroSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<SeriesHeroSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *SeriesHero*
 */
type SeriesHeroSliceVariation = SeriesHeroSliceDefault;

/**
 * SeriesHero Shared Slice
 *
 * - **API ID**: `series_hero`
 * - **Description**: SeriesHero
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type SeriesHeroSlice = prismic.SharedSlice<
  "series_hero",
  SeriesHeroSliceVariation
>;

declare module "@prismicio/client" {
  interface CreateClient {
    (
      repositoryNameOrEndpoint: string,
      options?: prismic.ClientConfig,
    ): prismic.Client<AllDocumentTypes>;
  }

  interface CreateWriteClient {
    (
      repositoryNameOrEndpoint: string,
      options: prismic.WriteClientConfig,
    ): prismic.WriteClient<AllDocumentTypes>;
  }

  interface CreateMigration {
    (): prismic.Migration<AllDocumentTypes>;
  }

  namespace Content {
    export type {
      BookDocument,
      BookDocumentData,
      HomepageDocument,
      HomepageDocumentData,
      HomepageDocumentDataSlicesSlice,
      MainNavigationDocument,
      MainNavigationDocumentData,
      MainNavigationDocumentDataNavigationlinksItem,
      MainNavigationDocumentDataSociallinksItem,
      PageDocument,
      PageDocumentData,
      PageDocumentDataSlicesSlice,
      PostDocument,
      PostDocumentData,
      PostDocumentDataSlicesSlice,
      SeriesDocument,
      SeriesDocumentData,
      SeriesDocumentDataSeriesbooksItem,
      AllDocumentTypes,
      CarouselSlice,
      CarouselSliceDefaultPrimary,
      CarouselSliceDefaultItem,
      CarouselSliceVariation,
      CarouselSliceDefault,
      ContentIndexSlice,
      ContentIndexSliceDefaultPrimary,
      ContentIndexSliceVariation,
      ContentIndexSliceDefault,
      HeroWithFigureSlice,
      HeroWithFigureSliceDefaultPrimary,
      HeroWithFigureSliceHeroWithFigureGradientPrimary,
      HeroWithFigureSliceHeroWithBackgroundImagePrimary,
      HeroWithFigureSliceVariation,
      HeroWithFigureSliceDefault,
      HeroWithFigureSliceHeroWithFigureGradient,
      HeroWithFigureSliceHeroWithBackgroundImage,
      MailerLiteSignUpSlice,
      MailerLiteSignUpSliceDefaultPrimary,
      MailerLiteSignUpSliceDefaultItem,
      MailerLiteSignUpSliceVariation,
      MailerLiteSignUpSliceDefault,
      ProseSlice,
      ProseSliceDefaultPrimary,
      ProseSliceVariation,
      ProseSliceDefault,
      SeriesHeroSlice,
      SeriesHeroSliceDefaultPrimarySeriesItem,
      SeriesHeroSliceDefaultPrimary,
      SeriesHeroSliceVariation,
      SeriesHeroSliceDefault,
    };
  }
}
