// This file is generated by Slice Machine. Update with care!

import HeroWithFigure from './HeroWithFigure';

export {
	HeroWithFigure,
};

export const components = {
	hero_with_figure: HeroWithFigure,
};
