// Code generated by Slice Machine. DO NOT EDIT.

import dynamic from "next/dynamic";

export const components = {
  carousel: dynamic(() => import("./Carousel")),
  hero_with_figure: dynamic(() => import("./HeroWithFigure")),
  mailer_lite_sign_up: dynamic(() => import("./NewsletterSignUp")),
  prose: dynamic(() => import("./Prose")),
  series_hero: dynamic(() => import("./SeriesHero")),
};
