// This file is generated by Slice Machine. Update with care!

import Carousel from './Carousel';
import HeroWithFigure from './HeroWithFigure';

export {
	Carousel,
	HeroWithFigure,
};

export const components = {
	carousel: Carousel,
	hero_with_figure: HeroWithFigure,
};
