import type { Metadata } from 'next'
import { Cormorant } from 'next/font/google'
import './globals.css'
// import Navbar from '@/components/Navbar'
// import { createClient } from '@/prismicio'
import Header from '@/components/layout/Header/Header'
import { PrismicPreview } from '@prismicio/next'
import { repositoryName } from '@/prismicio'
import Footer from '@/components/layout/Footer/Footer'

const cormorant = Cormorant({
  variable: '--font-heading-serif',
  subsets: ['latin'],
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default async function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  // const client = createClient()
  // const navigation = await client.getSingle('main_navigation')
  return (
    <html lang="en">
      <body className={`${cormorant.variable} antialiased`}>
        {/* <Navbar navigation={navigation} /> */}
        <Header />
        <main id="content" tabIndex={-1}>
          {children}
        </main>
        <Footer />
        <PrismicPreview repositoryName={repositoryName} />
      </body>
    </html>
  )
}
